"""update price model

Revision ID: cb79c37cb348
Revises: 34efc0cc0cf6
Create Date: 2026-08-15 15:24:34.566417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb79c37cb348'
down_revision: Union[str, Sequence[str], None] = '34efc0cc0cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silver_prices', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silver_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
